name: Linux Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libssl-dev

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake ..

    - name: Build
      run: |
        cd build
        make -j$(nproc)

    - name: Create Archive
      run: |
        export ARTIFACT_NAME="lc-linux-x86_64.tar.gz"
        mkdir -p release
        cp build/lc release/
        cp LICENSE release/ || touch release/LICENSE
        cp README.md release/ || touch release/README.md
        cd release
        tar -czf ../${ARTIFACT_NAME} *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: linux-binary
        path: lc-linux-x86_64.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: linux-binary
        path: artifacts

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: artifacts/lc-linux-x86_64.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
